ingress:
  enabled: false

service:
  type: ClusterIP
  port: 7007

postgresql:
  enabled: true
  auth:
    username: backstage
    password: backstage
    database: backstage_plugin_catalog

backstage:
  appConfig:
    app:
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: backstage
          password: backstage
          database: backstage_plugin_catalog

    # Catalog: entidades que Backstage mostrará
    catalog:
      locations:
        - type: url
          target: https://github.com/shovelmans/backstage/blob/main/catalog-info.yaml

    # Autenticación básica (Guest activado para pruebas)
    auth:
      environment: development
      providers:
        guest: {}
