ingress:
  enabled: false

service:
  type: ClusterIP
  port: 7007

backstage:
  appConfig:
    app:
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
      cors:
        origin: http://localhost:7007
