ingress:
  enabled: false

service:
  type: ClusterIP
  port: 7007

postgresql:
  enabled: true
  auth:
    username: backstage
    password: backstage
    database: backstage_plugin_catalog

backstage:
  appConfig:
    app:
      baseUrl: http://localhost:7007

    backend:
      baseUrl: http://localhost:7007
      database:
        client: pg
        connection:
          host: backstage-postgresql
          port: 5432
          user: backstage
          password: backstage
          database: backstage_plugin_catalog
      auth:
        keys:
          - secret: "super-secret-key-change-me"

    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/shovelmans/backstage/main/catalog-info.yaml

    auth:
      environment: development
      providers:
        guest: {}
